### ISSUE TITLE
Deploy cloud native database

### ISSUE THREAD

**Issue by faizzamzuri** [faizzamzuri/terraform-aws-lms#10]
Create database for Moodle in Amazon RDS for MariaDB

attribute | value
---------|------
allocated_storage | 10
db_name | "mydb"
engine | "mysql"
engine_version | "8.0"
instance_class | "db.t3.micro"
username | "foo"
password | "foobarbaz"
parameter_group_name | "default.mysql8.0"
skip_final_snapshot | true

Reference: [Terraform Best Practices](https://cloud.google.com/docs/terraform/best-practices/general-style-structure)

**Comment by rahmancloud** [comment]
@faizzamzuri 

1. Confirm database software used in EC2 instance.
1. Deploy the RDS instance with console.
   - Stick with suggested values (free-tier, cheapest).
   - Use the simplest configuration (existing VPC, existing subnet, etc.)
1. Write Terraform based on the deployed RDS.

**Comment by faizzamzuri** [comment]
1. Database software --> MariaDB

![mariadb](https://github.com/user-attachments/assets/d998c3fe-c943-4b7e-8cc7-8456c9addf22)

https://docs.bitnami.com/azure/apps/moodle/get-started/find-credentials-link-mariadb/ 
To identify which database server is used in your stack, run the command below:

test -d /opt/bitnami/mariadb && echo "MariaDB" || echo "MySQL"

output --> MariaDB

**Comment by faizzamzuri** [comment]
2. Deploy RDS using console.

Setting as below

attribute | value
---------|-------
Database creation method | standard
Engine type | mariadb
Engine version | 10.11.8
templates | Free tier
DB instance identifier  | database1
Master username | admin
Credentials management | self-managed
Master password | Database1!
DB Instance class | db.t3.micro
storage | gp2, 20GB
connectivity | Don’t connect to an EC2 compute resource
Network type | ipv4
VPC | Default vpc
DB Subnet group | default
Public access | no
VPC security group (firewall)  | Create new - MariaDB_SG
Availability Zone | No preference
Certificate authority - optional | default
Database authentication | Password authentication
Estimated Monthly costs | DB instance 18.98 USD, Storage 2.76 USD, Total - 21.74 USD


Setting up mariadb using console, and using free tier, but there are still some cost per month.

**Comment by rahmancloud** [comment]
Delete if not in use. Re-create using Terraform when needed.

**Comment by faizzamzuri** [comment]
3. Terraform mariaDB - 

resource "aws_db_instance" "database1" {
  allocated_storage    = 20
  db_name              = "database1"
  engine               = "mariadb"
  engine_version       = "10.11.8"
  instance_class       = "db.t3.micro"
  username             = "admin"
  password             = "Database1!"
  parameter_group_name = "default.mariadb10.11"
  skip_final_snapshot  = true
  copy_tags_to_snapshot = true
}

**Comment by rahmancloud** [comment]
Boleh terus paste dalam `database.tf` di branch `database`.
